import Link from "next/link";
import {
  Sparkles,
  ArrowRight,
  Brain,
  Target,
  BarChart3,
  CheckCircle2,
  Zap,
  Shield,
  Layers,
  Award,
  ChevronRight,
} from "lucide-react";
import { auth } from "@/auth";

export default async function LandingPage() {
  const session = await auth();

  return (
    <div className="flex-1 flex flex-col">
      {/* Hero Section */}
      <section className="relative overflow-hidden pt-20 pb-24 md:pt-28 md:pb-32">
        {/* Background glow effects */}
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-indigo-600/15 rounded-full blur-[140px] pointer-events-none" />
        <div className="absolute top-1/3 left-1/4 w-[350px] h-[350px] bg-violet-600/10 rounded-full blur-[100px] pointer-events-none" />

        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 text-center">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/25 text-indigo-300 text-xs sm:text-sm font-medium mb-8 backdrop-blur-sm shadow-inner shadow-indigo-500/10">
            <Sparkles className="w-4 h-4 text-indigo-400" />
            <span>Next-Generation Technical Interview Simulation</span>
          </div>

          {/* Main Headline */}
          <h1 className="text-4xl sm:text-6xl lg:text-7xl font-extrabold tracking-tight text-white max-w-4xl mx-auto leading-[1.15]">
            Master technical interviews with{" "}
            <span className="bg-gradient-to-r from-indigo-400 via-violet-300 to-indigo-200 bg-clip-text text-transparent">
              AI-driven precision
            </span>
          </h1>

          {/* Subtitle */}
          <p className="mt-6 text-base sm:text-lg md:text-xl text-slate-300 max-w-2xl mx-auto leading-relaxed">
            Practice role-specific, scenario-based questions generated by Gemini AI. Get instant grading, constructive weaknesses analysis, and actionable study plans.
          </p>

          {/* CTAs */}
          <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4">
            {session ? (
              <Link
                href="/dashboard"
                className="w-full sm:w-auto flex items-center justify-center gap-2.5 px-8 py-3.5 rounded-2xl text-base font-semibold text-white bg-indigo-600 hover:bg-indigo-500 active:scale-[0.98] transition-all shadow-xl shadow-indigo-600/25"
              >
                <span>Go to Dashboard</span>
                <ArrowRight className="w-5 h-5" />
              </Link>
            ) : (
              <>
                <Link
                  href="/signup"
                  className="w-full sm:w-auto flex items-center justify-center gap-2.5 px-8 py-3.5 rounded-2xl text-base font-semibold text-white bg-indigo-600 hover:bg-indigo-500 active:scale-[0.98] transition-all shadow-xl shadow-indigo-600/25"
                >
                  <span>Start Free Practice</span>
                  <ArrowRight className="w-5 h-5" />
                </Link>
                <Link
                  href="/login"
                  className="w-full sm:w-auto flex items-center justify-center gap-2 px-8 py-3.5 rounded-2xl text-base font-medium text-slate-300 hover:text-white bg-navy-900 border border-slate-800 hover:bg-slate-800/80 transition-all"
                >
                  <span>Sign In</span>
                </Link>
              </>
            )}
          </div>

          {/* Trust badges */}
          <div className="mt-12 flex flex-wrap items-center justify-center gap-6 sm:gap-10 text-xs sm:text-sm text-slate-400">
            <span className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" /> Free Tier Google Gemini AI
            </span>
            <span className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" /> Multi-Dimensional Rubrics
            </span>
            <span className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" /> Personalized Study Roadmaps
            </span>
          </div>

          {/* Product UI Mockup / Showcase */}
          <div className="mt-16 relative mx-auto max-w-4xl rounded-3xl p-2 sm:p-3 bg-gradient-to-b from-indigo-500/20 via-slate-800/40 to-slate-900/60 border border-indigo-500/20 shadow-2xl backdrop-blur-xl">
            <div className="rounded-2xl bg-navy-950 p-6 sm:p-8 border border-slate-800/80 text-left space-y-6">
              {/* Mock Question Preview */}
              <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-4">
                <div className="flex items-center gap-2">
                  <span className="px-3 py-1 rounded-lg bg-indigo-600/20 text-indigo-400 font-semibold text-xs border border-indigo-500/30">
                    Live Question 3 of 5
                  </span>
                  <span className="px-2.5 py-1 rounded-lg bg-slate-800 text-slate-300 text-xs">
                    React & State Management
                  </span>
                </div>
                <span className="px-2.5 py-1 rounded-lg bg-emerald-500/10 text-emerald-400 text-xs font-semibold uppercase">
                  Score: 8.8 / 10
                </span>
              </div>

              <p className="text-base sm:text-lg font-medium text-slate-100">
                &ldquo;Explain when you would reach for React Server Components versus standard client components, and how state serialization affects data passing across that boundary.&rdquo;
              </p>

              {/* Mock AI Feedback Snippet */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
                <div className="p-3.5 rounded-xl bg-emerald-950/20 border border-emerald-500/20 text-xs text-slate-300">
                  <span className="text-emerald-400 font-semibold block mb-1">
                    ✓ Strong Correctness & Depth
                  </span>
                  Accurately highlighted bundle size reduction, direct DB access, and JSON-serializable props.
                </div>
                <div className="p-3.5 rounded-xl bg-indigo-950/20 border border-indigo-500/20 text-xs text-slate-300">
                  <span className="text-indigo-400 font-semibold block mb-1">
                    ★ Pro Tip for Real Interviews
                  </span>
                  Mention Next.js Server Actions and suspense streaming boundaries to stand out as a senior engineer.
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 3 Core Feature Blocks (SPEC Section 7) */}
      <section className="py-20 bg-navy-900/50 border-t border-b border-slate-800/80 relative">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-2xl mx-auto mb-16">
            <span className="text-xs font-bold uppercase tracking-wider text-indigo-400">
              Complete Preparation Workflow
            </span>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight mt-2">
              Engineered to transform how you interview
            </h2>
            <p className="text-sm sm:text-base text-slate-400 mt-3">
              Standard interview question lists don&apos;t simulate real-world conversations. PrepAI provides real-time dialogue and tailored feedback.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Feature 1 */}
            <div className="p-8 rounded-3xl bg-navy-900/90 border border-slate-800 hover:border-indigo-500/40 shadow-xl transition-all duration-300 flex flex-col justify-between group">
              <div>
                <div className="w-12 h-12 rounded-2xl bg-indigo-600/15 border border-indigo-500/30 text-indigo-400 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                  <Brain className="w-6 h-6" />
                </div>
                <h3 className="text-xl font-bold text-white mb-3">
                  Dynamic Question Generation
                </h3>
                <p className="text-sm text-slate-400 leading-relaxed">
                  Questions are generated live by Gemini AI based on your experience level, chosen skills, and target difficulty. No static flashcards or memorized question banks.
                </p>
              </div>
              <ul className="mt-6 pt-6 border-t border-slate-800 space-y-2 text-xs text-slate-300">
                <li className="flex items-center gap-2">
                  <CheckCircle2 className="w-3.5 h-3.5 text-indigo-400" /> Conceptual, practical & scenario tests
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle2 className="w-3.5 h-3.5 text-indigo-400" /> Calibrated for Fresher to Senior
                </li>
              </ul>
            </div>

            {/* Feature 2 */}
            <div className="p-8 rounded-3xl bg-navy-900/90 border border-slate-800 hover:border-indigo-500/40 shadow-xl transition-all duration-300 flex flex-col justify-between group">
              <div>
                <div className="w-12 h-12 rounded-2xl bg-emerald-600/15 border border-emerald-500/30 text-emerald-400 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                  <Target className="w-6 h-6" />
                </div>
                <h3 className="text-xl font-bold text-white mb-3">
                  Multi-Dimensional Evaluation
                </h3>
                <p className="text-sm text-slate-400 leading-relaxed">
                  Every answer is graded on correctness (50%), depth (30%), and communication clarity (20%). Receive concrete strengths, identified weaknesses, and a concise model answer.
                </p>
              </div>
              <ul className="mt-6 pt-6 border-t border-slate-800 space-y-2 text-xs text-slate-300">
                <li className="flex items-center gap-2">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" /> Numerical scoring from 0 to 10
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" /> Actionable tips for each question
                </li>
              </ul>
            </div>

            {/* Feature 3 */}
            <div className="p-8 rounded-3xl bg-navy-900/90 border border-slate-800 hover:border-indigo-500/40 shadow-xl transition-all duration-300 flex flex-col justify-between group">
              <div>
                <div className="w-12 h-12 rounded-2xl bg-violet-600/15 border border-violet-500/30 text-violet-400 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                  <BarChart3 className="w-6 h-6" />
                </div>
                <h3 className="text-xl font-bold text-white mb-3">
                  Comprehensive Reports & Trends
                </h3>
                <p className="text-sm text-slate-400 leading-relaxed">
                  Finish an interview to unlock a full assessment: topic-by-topic competency score bars, personalized study actions, and an interactive score progression trend chart.
                </p>
              </div>
              <ul className="mt-6 pt-6 border-t border-slate-800 space-y-2 text-xs text-slate-300">
                <li className="flex items-center gap-2">
                  <CheckCircle2 className="w-3.5 h-3.5 text-violet-400" /> Readiness level categorization
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle2 className="w-3.5 h-3.5 text-violet-400" /> Chronological score line charts
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* How it Works Section */}
      <section className="py-20">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-xl mx-auto mb-16">
            <span className="text-xs font-bold uppercase tracking-wider text-indigo-400">
              Simple 3-Step Loop
            </span>
            <h2 className="text-3xl font-extrabold text-white tracking-tight mt-2">
              How PrepAI Works
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 relative">
            <div className="p-6 rounded-2xl bg-navy-900/60 border border-slate-800 text-center space-y-3">
              <div className="w-10 h-10 rounded-full bg-indigo-600 text-white font-bold flex items-center justify-center mx-auto text-sm">
                1
              </div>
              <h3 className="text-lg font-bold text-white">Profile Your Skills</h3>
              <p className="text-xs sm:text-sm text-slate-400">
                Add your technical proficiencies (React, TypeScript, SQL, Docker) and choose your target role.
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-navy-900/60 border border-slate-800 text-center space-y-3">
              <div className="w-10 h-10 rounded-full bg-indigo-600 text-white font-bold flex items-center justify-center mx-auto text-sm">
                2
              </div>
              <h3 className="text-lg font-bold text-white">Simulate the Interview</h3>
              <p className="text-xs sm:text-sm text-slate-400">
                Answer AI-generated questions one by one with immediate feedback and model answers after each turn.
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-navy-900/60 border border-slate-800 text-center space-y-3">
              <div className="w-10 h-10 rounded-full bg-indigo-600 text-white font-bold flex items-center justify-center mx-auto text-sm">
                3
              </div>
              <h3 className="text-lg font-bold text-white">Review & Level Up</h3>
              <p className="text-xs sm:text-sm text-slate-400">
                Examine your synthesized score report, follow your customized study plan, and track improvements over time.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Bottom CTA Banner */}
      <section className="py-16 border-t border-slate-800 bg-navy-900/40">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center space-y-6">
          <h2 className="text-3xl sm:text-4xl font-extrabold text-white">
            Ready to ace your next technical interview?
          </h2>
          <p className="text-slate-400 max-w-xl mx-auto text-sm sm:text-base">
            Join thousands of developers leveling up their technical communication with real-time AI feedback.
          </p>
          <div className="pt-2">
            <Link
              href={session ? "/dashboard" : "/signup"}
              className="inline-flex items-center gap-2 px-8 py-3.5 rounded-2xl text-base font-semibold text-white bg-indigo-600 hover:bg-indigo-500 shadow-xl shadow-indigo-600/30 transition-all"
            >
              <span>{session ? "Open Your Dashboard" : "Create Free Account"}</span>
              <ArrowRight className="w-5 h-5" />
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-800/80 py-8 bg-navy-950">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-slate-500">
          <div className="flex items-center gap-2 text-slate-400 font-semibold">
            <Sparkles className="w-4 h-4 text-indigo-400" />
            <span>PrepAI &copy; {new Date().getFullYear()}</span>
          </div>
          <p>Built for engineers, by engineers.</p>
        </div>
      </footer>
    </div>
  );
}
